title:              For my shine
logo:               Ashhyun
email:              abyssinial@naver.com
description:        데이터과학 프로그래머입니다
author:             Ashhyun
baseurl:            ""
url:                "https://ashhyun.github.io"

# Social Profiles
twitter_username:   
github_username:    Ashhyun
facebook_username:  
instagram_username:  abyssinial
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-159363886-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
